### ISSUE TITLE
Error when building vignettes due to devtools new versions and other packages issues

### ISSUE THREAD

**Issue by aragaoalexander** [ehassler/MontgomeryDAE#2]
I tried installing MontgomeryDAE, but it fails, showing 

`Erro: Failed to install 'MontgomeryDAE' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E>   'inst/doc/chapter07.html'
E>   'inst/doc/chapter08.html'
E>   'inst/doc/chapter09.html'
E>   'inst/doc/chapter10.html'
E>   'inst/doc/chapter11.html'
E>   'inst/doc/chapter12.html'
E>   'inst/doc/chapter13.html'
E>   'inst/doc/chapter14.html'
E>   'inst/doc/chapter15.html'
E> Run R CMD build without --no-build-vignettes to re-create`

I assumed this happened because newest devtools versions have changed `build_vignettes` default value from TRUE to FALSE. Using the argument `build vignettes = TRUE` solves this. However, installation fails again due to missing packages: `kableExtra`, `lmerTest`, `pwr`, `emmeans`, `DOE.base`, `FrF2`. I'm not sure if these were supposed to be installed automatically, but installing them solved all issues.

**Comment by aragaoalexander** [comment]
Another issue popped up:

`   --- re-building 'chapter05.Rmd' using rmarkdown
   Loading required package: ggplot2
   Quitting from lines 192-197 (chapter05.Rmd) 
   Error: processing vignette 'chapter05.Rmd' failed with diagnostics:
   contrasts apply only to factors
   --- failed re-building 'chapter05.Rmd'`

Apparently some `ggplot2` function throws an error?

**Comment by ehassler** [comment]
Thanks for reporting these!  It looks like packages needed only in vignettes are "supposed" to be listed under Suggests instead of Imports.  Building the vignettes is also facing a problem where qualityTools has been removed from CRAN, so expecting the user to build the vignettes may be unreasonable.  

To address this I pushed a compiled source package into releases and changed the installation instructions to install that package instead of using devtools to install from github.  This way you get the html help files and all of the data sets.  Then you can install whichever packages you need for the chapter on which you're working.

For some reason it's not building these as vignettes though, which I hope to address later, but for now the html help files are accessible with `help(package='MontgomeryDAE')`.

Regarding the second issue you mentioned, I fixed that by explicitly converting a column to a factor then applying the contrast, and it seems to build fine.  It should be working in the 10.1 version.

I'm going to mark this issue as closed but let me know if this solution works for you.

**Comment by aragaoalexander** [comment]
Apparently, the solution worked. I was able to install the package and load the help files and a couple of data sets successfully. I'll let you know if something else pops up, but thank you for the quick feedback and fix!
